saque = int(input("Qual valor desejado para o Saque:"))
auxiliar = saque
notas = 0
if saque >= 100:
    while saque >= 100:
        saque = saque - 100
        notas += 1
if 50 <= saque < 100:
    while saque >= 50:
        saque = saque - 50
        notas += 1
if 20 <= saque < 50:
    while saque >= 20:
        saque = saque - 20
        notas += 1
if 10 <= saque < 20:
    while saque >= 10:
        saque = saque - 10
        notas += 1
if 5 <= saque < 10:
    while saque >= 5:
        saque = saque - 5
        notas += 1
if 2 <= saque < 5:
    while saque >= 2:
        saque = saque - 2
        notas += 1
if 1 <= saque < 2:
    while saque >= 1:
        saque = saque - 1
        notas += 1
print(f"Serão utilizadas {notas} notas para o saque de R${auxiliar}")